# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Quinaux/Desktop/Projet/Audio-Effect-Box/PYNQ-Z2_C.xdc

# Block Designs: bd/Audio_Effect_Box/Audio_Effect_Box.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Audio_Effect_Box || ORIG_REF_NAME==Audio_Effect_Box} -quiet] -quiet

# IP: bd/Audio_Effect_Box/ip/Audio_Effect_Box_processing_system7_0_0/Audio_Effect_Box_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Audio_Effect_Box_processing_system7_0_0 || ORIG_REF_NAME==Audio_Effect_Box_processing_system7_0_0} -quiet] -quiet

# IP: bd/Audio_Effect_Box/ip/Audio_Effect_Box_i2s_receiver_0_1/Audio_Effect_Box_i2s_receiver_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Audio_Effect_Box_i2s_receiver_0_1 || ORIG_REF_NAME==Audio_Effect_Box_i2s_receiver_0_1} -quiet] -quiet

# IP: bd/Audio_Effect_Box/ip/Audio_Effect_Box_i2s_transmitter_0_1/Audio_Effect_Box_i2s_transmitter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Audio_Effect_Box_i2s_transmitter_0_1 || ORIG_REF_NAME==Audio_Effect_Box_i2s_transmitter_0_1} -quiet] -quiet

# IP: bd/Audio_Effect_Box/ip/Audio_Effect_Box_xbar_0/Audio_Effect_Box_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Audio_Effect_Box_xbar_0 || ORIG_REF_NAME==Audio_Effect_Box_xbar_0} -quiet] -quiet

# IP: bd/Audio_Effect_Box/ip/Audio_Effect_Box_ps7_0_axi_periph_2/Audio_Effect_Box_ps7_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Audio_Effect_Box_ps7_0_axi_periph_2 || ORIG_REF_NAME==Audio_Effect_Box_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/Audio_Effect_Box/ip/Audio_Effect_Box_rst_ps7_0_100M_2/Audio_Effect_Box_rst_ps7_0_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Audio_Effect_Box_rst_ps7_0_100M_2 || ORIG_REF_NAME==Audio_Effect_Box_rst_ps7_0_100M_2} -quiet] -quiet

# IP: bd/Audio_Effect_Box/ip/Audio_Effect_Box_axi_iic_0_0/Audio_Effect_Box_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Audio_Effect_Box_axi_iic_0_0 || ORIG_REF_NAME==Audio_Effect_Box_axi_iic_0_0} -quiet] -quiet

# IP: bd/Audio_Effect_Box/ip/Audio_Effect_Box_auto_pc_0/Audio_Effect_Box_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Audio_Effect_Box_auto_pc_0 || ORIG_REF_NAME==Audio_Effect_Box_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Quinaux/Desktop/Projet/Audio-Effect-Box/Audio_Effect_Box.gen/sources_1/bd/Audio_Effect_Box/Audio_Effect_Box_ooc.xdc
