# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Christos/Desktop/Projet/Audio_Effect_Box/Audio_Effect_Box.srcs/sources_1/bd/Audio_Effect_Box/ip/Audio_Effect_Box_axi_apb_bridge_0_0/Audio_Effect_Box_axi_apb_bridge_0_0.xci
# IP: The module: 'Audio_Effect_Box_axi_apb_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Christos/Desktop/Projet/Audio_Effect_Box/Audio_Effect_Box.gen/sources_1/bd/Audio_Effect_Box/ip/Audio_Effect_Box_axi_apb_bridge_0_0/Audio_Effect_Box_axi_apb_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Audio_Effect_Box_axi_apb_bridge_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Christos/Desktop/Projet/Audio_Effect_Box/Audio_Effect_Box.srcs/sources_1/bd/Audio_Effect_Box/ip/Audio_Effect_Box_axi_apb_bridge_0_0/Audio_Effect_Box_axi_apb_bridge_0_0.xci
# IP: The module: 'Audio_Effect_Box_axi_apb_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Christos/Desktop/Projet/Audio_Effect_Box/Audio_Effect_Box.gen/sources_1/bd/Audio_Effect_Box/ip/Audio_Effect_Box_axi_apb_bridge_0_0/Audio_Effect_Box_axi_apb_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Audio_Effect_Box_axi_apb_bridge_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
